import './prepare406.mjs';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';
const version='4.0.11';
const html=(await fs.readFile('app/index.html','utf8')).replace('name="titv-desktop-version" content="4.0.6"','name="titv-desktop-version" content="'+version+'"');
await fs.writeFile('app/index.html',html);
const manifest=JSON.parse(await fs.readFile('qa/halfday-manifest.json','utf8'));
manifest.desktopVersion=version;
manifest.desktopSha256=crypto.createHash('sha256').update(html).digest('hex');
manifest.previousChannels=['GitHub 4.0.5','Netlify 4.0.10'];
for(const file of ['app/repair-info.json','qa/halfday-manifest.json'])await fs.writeFile(file,JSON.stringify(manifest,null,2));
const release='web-overlay/RELEASE_NOTES_V3.33.9.txt';
await fs.writeFile(release,(await fs.readFile(release,'utf8')).replace('Desktop 4.0.6','Desktop '+version));
console.log('Unified desktop version: '+version);
