import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {parse} from 'acorn';
import {chromium} from 'playwright';
const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const testSource=await fs.readFile('test405.mjs','utf8');
const fixtureNode=parse(testSource,{ecmaVersion:'latest',sourceType:'module'}).body.find(n=>n.type==='FunctionDeclaration'&&n.id?.name==='fixtureHTML');
const fixtureHTML=new Function('parse','assert','return ('+testSource.slice(fixtureNode.start,fixtureNode.end)+');')(parse,assert);
const hook=`window.__halfday={get:()=>deepClone(state.leaves),open:openLeaveModal,read:readLeaveForm,close:()=>closeModal('leaveModal'),usage:formatLeaveUsage,conflict:leaveConflictsWithEvent,print:()=>buildSchedulePrintSvg(currentWeek),excel:exportScheduleExcelPageMatch,map:l=>{const before=currentOrg;currentOrg={id:'QAORG'};try{return mapLeaveRow(l)}finally{currentOrg=before}},restore:rows=>{state.leaves=rows.map(x=>({id:x.id,employeeId:x.employee_id,date:x.work_date,type:canonicalLeaveType(x.leave_type),note:x.note||'',meta:x.leave_meta||{}}));renderAll();}};`;
const web=await fs.readFile('web-overlay/index.html','utf8'),desktop=await fs.readFile('app/index.html','utf8');
const module=h=>h.match(/<script\s+type="module"[^>]*>([\s\S]*?)<\/script>/)[1];
assert.equal(module(desktop),module(web).replaceAll('${location.origin}','https://titv-engineering-scheduler.netlify.app'));
const fixture=h=>fixtureHTML(h).replace('window.__qa={',()=>hook+'\nwindow.__qa={');
const pages={web:fixture(web),desktop:fixture(desktop)};
const server=http.createServer(async(req,res)=>{const p=new URL(req.url,'http://localhost').pathname;if(p==='/web'||p==='/desktop'){res.writeHead(200,{'Content-Type':'text/html;charset=utf-8'});res.end(pages[p.slice(1)]);return;}if(p.startsWith('/.netlify/functions/')){res.writeHead(200,{'Content-Type':'application/json'});res.end('{"dates":{}}');return;}if(p.includes('..')){res.writeHead(400);res.end();return;}try{const file=path.join('app',p),data=await fs.readFile(file);res.writeHead(200,{'Content-Type':({'.mjs':'text/javascript','.js':'text/javascript','.css':'text/css','.png':'image/png','.ico':'image/x-icon'})[path.extname(file)]||'application/octet-stream'});res.end(data);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
await fs.mkdir('qa/screenshots',{recursive:true});const browser=await chromium.launch();const report={scope:'Isolated fixture data; production writes and notifications blocked. Existing cloud JSONB contract tested by serialization and rehydration, not a real employee update.',webCore:'V3.33.9',desktop:'4.0.6',sharedModuleHash:sha(module(web)),cases:[],passed:false};
try{
for(const flavor of ['web','desktop']){
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,serviceWorkers:'block'});await context.route('**/*',r=>r.request().url().startsWith(origin)||r.request().url().startsWith('data:')?r.continue():r.abort());await context.routeWebSocket('**/*',ws=>ws.close());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto(origin+'/'+flavor);await page.waitForFunction(()=>Boolean(window.__halfday));await page.evaluate(()=>{window.__qa.view('leave');window.__halfday.open(null,{employeeId:'QA1',date:'2026-09-28'});});
 await page.selectOption('#leaveType','半天');assert.equal(await page.inputValue('#leaveUnit'),'half_day');assert.equal(await page.locator('#leaveTimeSection').isVisible(),true);await page.selectOption('#leaveHalfDayPeriod','am');assert.equal(await page.inputValue('#leaveStartTime'),'09:00');assert.equal(await page.inputValue('#leaveEndTime'),'13:00');
 await page.screenshot({path:'qa/screenshots/'+flavor+'-halfday-form.png'});await page.locator('#leaveForm button[type="submit"]').click();await page.waitForFunction(()=>window.__halfday.get().length===1&&!document.getElementById('leaveModal').classList.contains('open'));
 let l=(await page.evaluate(()=>window.__halfday.get()))[0];assert.equal(l.meta.unit,'hour');assert.equal(l.meta.duration,'half_day');assert.equal(l.meta.day_fraction,0.5);assert.equal(await page.evaluate(l=>window.__halfday.usage([l]),l),'0.5日');
 const conflict=await page.evaluate(l=>[window.__halfday.conflict(l,{start:'08:00',end:'09:00'}),window.__halfday.conflict(l,{start:'10:00',end:'11:00'}),window.__halfday.conflict(l,{start:'13:00',end:'17:00'})],l);assert.deepEqual(conflict,[false,true,false]);
 await page.evaluate(id=>window.__halfday.open(id),l.id);assert.equal(await page.inputValue('#leaveEndTime'),'13:00');await page.selectOption('#leaveHalfDayPeriod','pm');await page.locator('#leaveForm button[type="submit"]').click();await page.waitForFunction(()=>window.__halfday.get()[0].meta.start_time==='13:00');l=(await page.evaluate(()=>window.__halfday.get()))[0];
 const row=await page.evaluate(l=>window.__halfday.map(l),l);assert.deepEqual(row.leave_meta,l.meta);await page.evaluate(rows=>window.__halfday.restore(rows),[row]);await page.evaluate(id=>window.__halfday.open(id),l.id);assert.equal(await page.inputValue('#leaveHalfDayPeriod'),'pm');assert.equal(await page.inputValue('#leaveStartTime'),'13:00');
 await page.selectOption('#leaveType','休O');await page.selectOption('#leaveUnit','day');await page.locator('#leaveForm button[type="submit"]').click();await page.waitForFunction(()=>window.__halfday.get()[0].meta.unit==='day');l=(await page.evaluate(()=>window.__halfday.get()))[0];assert.equal(l.type,'休O');assert.equal(l.meta.duration,undefined);assert.equal(l.meta.start_time,'');assert.equal(await page.evaluate(l=>window.__halfday.usage([l]),l),'1日');
 await page.evaluate(id=>window.__halfday.open(id),l.id);await page.selectOption('#leaveUnit','half_day');await page.selectOption('#leaveHalfDayPeriod','am');await page.locator('#leaveForm button[type="submit"]').click();await page.waitForFunction(()=>window.__halfday.get()[0].meta.duration==='half_day');l=(await page.evaluate(()=>window.__halfday.get()))[0];assert.equal(l.type,'休O');
 await page.evaluate(id=>window.__halfday.open(id),l.id);await page.fill('#leaveStartTime','17:00');await page.fill('#leaveEndTime','13:00');assert.equal(await page.evaluate(()=>{try{window.__halfday.read();return false;}catch{return true;}}),true);await page.evaluate(()=>window.__halfday.close());
 const image=await page.evaluate(()=>window.__qa.image());assert(image.includes('09:00–13:00'));const print=await page.evaluate(()=>window.__halfday.print());assert(print.includes('半天'));assert(print.includes('09:00'));
 await page.evaluate(()=>window.__qa.view('schedule'));const downloadPromise=page.waitForEvent('download');await page.evaluate(()=>window.__halfday.excel());const dl=await downloadPromise;const dest='qa/'+flavor+'-halfday.xlsx';await dl.saveAs(dest);const bytes=await fs.readFile(dest);const xml=await page.evaluate(async data=>{const zip=await JSZip.loadAsync(Uint8Array.from(data));return zip.file('xl/worksheets/sheet1.xml').async('string');},[...bytes]);assert(xml.includes('半天'));assert(xml.includes('09:00–13:00'));
 for(let i=0;i<100;i++)await page.evaluate(()=>window.__qa.render());assert.equal(await page.locator('svg.tribal-icon').count(),48);assert.equal(await page.locator('[data-titv-icon]').count(),48);
 await page.evaluate(()=>window.__qa.view('leave'));await page.screenshot({path:'qa/screenshots/'+flavor+'-halfday-saved.png'});
 await page.setViewportSize({width:390,height:844});await page.evaluate(id=>window.__halfday.open(id),l.id);await page.screenshot({path:'qa/screenshots/'+flavor+'-halfday-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true);await page.evaluate(()=>window.__halfday.close());await page.setViewportSize({width:1440,height:1000});
 await page.evaluate(id=>window.__halfday.open(id),l.id);await page.locator('#deleteLeaveBtn').click();await page.waitForFunction(()=>window.__halfday.get().length===0);assert.deepEqual(errors,[]);
 report.cases.push({client:flavor,createAM:true,editPM:true,metadataRoundtrip:true,halfDayCount:0.5,conflicts,fullDayConversion:true,preservedInternalCode:true,invalidTimeRejected:true,pngLabel:true,printLabel:true,excelLabel:true,delete:true,stableIcons:48,pageErrors:errors});await context.close();
}
report.passed=true;
}catch(error){report.error=error.stack;throw error;}finally{await fs.writeFile('qa/halfday-test-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();await new Promise(r=>server.close(r));}
